### ISSUE TITLE
Safemode crash 

### ISSUE THREAD

**Issue by rebelraiders101** [cgm616/cgm616.github.io#1]
There's a crash to safe mode if a volume button is pressed as the banner is dismissing (animation). To replicate, change volume and as the banner animation is sliding out, change the volume again. Timing is semi-important to replicate this.

**Comment by cgm616** [comment]
Thank you so much! This seems to be the exact same as a bug I found a
while ago, but was impossible to test and replicate. Now I know the
steps to replication. Follow progress on this bug at issue #1.


On Sat, Sep 24, 2016, at 07:31 PM, rebelraiders101 wrote:
> There's a crash to safe mode if a volume button is pressed as the
> banner is dismissing (animation). To replicate, change volume and as
> the banner animation is sliding out, change the volume again. Timing
> is semi-important to replicate this.
> — You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub[1], or mute the
> thread[2].
>


Links:

  1. https://github.com/cgm616/cgm616.github.io/issues/1

**Comment by cgm616** [comment]
Not relevant to this repo, however. The issue on the VolumeBar9 repo has been updated.
